/** Provides models of taint flow in `org.springframework.web.util` */
import java

/** Provides models of taint flow in `org.springframework.web.util` */
module SpringWebUtil {
  private class FlowSummaries extends SummaryModelCsv {
    override predicate row(string row) {
      row = [
        "org.springframework.web.util;UriTemplateHandler;true;expand;(String,Map);;Argument[-1..1];ReturnValue;taint",
        "org.springframework.web.util;AbstractUriTemplateHandler;true;expandInternal;;;Argument[-1..1];ReturnValue;taint",
        "org.springframework.web.util;AbstractUriTemplateHandler;true;getBaseUrl;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;AbstractUriTemplateHandler;true;setBaseUrl;;;Argument[0];Argument[-1];taint",
        "org.springframework.web.util;AbstractUriTemplateHandler;true;setDefaultUriValuables;;;Argument[0];Argument[-1];taint",
        "org.springframework.web.util;DefaultUriTemplateHandler;true;setDefaultUriValuables;;;Argument[0];Argument[-1];taint",
        // note for review: the `content` of this wrapper is determined by what's written to it; there's a function `getWriter()`
        //   that gets a `PrintWriter`; is there a way to route writes to that writer to the receiver of the `getWriter` call?
        "org.springframework.web.util;ContentCachingRequestWrapper;false;getContentAsByteArray;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;ContentCachingRequestWrapper;true;copyBodyToResponse;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;ContentCachingRequestWrapper;true;getContentAsByteArray;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;ContentCachingRequestWrapper;true;getContentInputStream;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;ContentCachingRequestWrapper;true;sendError;;;Argument[0];Argument[-1];taint",
        "org.springframework.web.util;ContentCachingRequestWrapper;true;sendRedirect;;;Argument[0];Argument[-1];taint",
        "org.springframework.web.util;ContentCachingRequestWrapper;true;addHeader;;;Argument[0..1];Argument[-1];taint",
        // note for review: adds a cookie to argument 0; this depends on how we intend to model taint with `HttpServletResponse`s
        "org.springframework.web.util;CookieGenerator;false;addCookie;;;Argument[1];Argument[0];taint",
        // note for review: unsure of the perf impact these will have, and more than likely not very relevant.
        "org.springframework.web.util;CookieGenerator;false;getCookieDomain;;;SyntheticField org.springframework.web.util.CookieGenerator.cookieDomain of Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;CookieGenerator;false;setCookieDomain;;;Argument[0];SyntheticField org.springframework.web.util.CookieGenerator.cookieDomain of Argument[-1];taint",
        "org.springframework.web.util;CookieGenerator;false;getCookieName;;;SyntheticField org.springframework.web.util.CookieGenerator.cookieName of Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;CookieGenerator;false;setCookieName;;;Argument[0];SyntheticField org.springframework.web.util.CookieGenerator.cookieName of Argument[-1];taint",
        "org.springframework.web.util;CookieGenerator;false;getCookiePath;;;SyntheticField org.springframework.web.util.CookieGenerator.cookiePath of Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;CookieGenerator;false;setCookiePath;;;Argument[0];SyntheticField org.springframework.web.util.CookieGenerator.cookiePath of Argument[-1];taint",
        "org.springframework.web.util;DefaultUriBuilderFactory;false;DefaultUriBuilderFactory;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;DefaultUriBuilderFactory;false;builder;;;SyntheticField org.springframework.web.util.DefaultUriBuilderFactory.defaultUriVariables of Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;DefaultUriBuilderFactory;false;expand;;;Argument[-1..1];ReturnValue;taint",
        "org.springframework.web.util;DefaultUriBuilderFactory;false;expand;;;SyntheticField org.springframework.web.util.DefaultUriBuilderFactory.defaultUriVariables of Argument[-1];ReturnValue;taint",
        // note for review: these are maps but I think the keys are irrelevant for taint, so I'm ignoring them (or I could put a `MapValue of` before every synthetic field)
        "org.springframework.web.util;DefaultUriBuilderFactory;false;getDefaultUriVariables;;;SyntheticField org.springframework.web.util.DefaultUriBuilderFactory.defaultUriVariables of Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;DefaultUriBuilderFactory;false;setDefaultUriVariables;;;Argument[0];SyntheticField org.springframework.web.util.DefaultUriBuilderFactory.defaultUriVariables of Argument[-1];ReturnValue;taint",
        // note for review: I couldn't find any default xss sanitizer definitions so I've assumed I shouldn't model html escape functions for taint
        "org.springframework.web.util;HtmlUtils;false;htmlUnescape;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;ServletContextPropertyUtils;false;resolvePlaceholders;;;Argument[0..1];ReturnValue;taint",
        "org.springframework.web.util;ServletRequestPathUtils;false;getCachedPath;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;ServletRequestPathUtils;false;getCachedPathValue;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;ServletRequestPathUtils;false;getParsedRequestPath;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;ServletRequestPathUtils;false;parseAndCache;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;ServletRequestPathUtils;false;setParsedRequestPath;;;Argument[0];Argument[1];taint",
        "org.springframework.web.util;UriBuilder;true;build;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;build;(java.util.Map<java.lang.String,?>);;MapValue of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;build;(java.lang.Object...);;element of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;fragment;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;host;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;path;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;pathSegment;;;Element of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;port;(java.lang.String);;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;query;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;queryParam;;;Argument[0];ReturnValue;taint",
        // note for review: using `Element of` for `Object...` here
        "org.springframework.web.util;UriBuilder;true;queryParam;;;Element of Argument[1];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;queryParamIfPresent;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;queryParamIfPresent;;;Element of Argument[1];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;queryParams;;;MapValue of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;queryParams;;;MapKey of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;replacePath;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;replaceQuery;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;replaceQueryParam;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;replaceQueryParam;;;Element of Argument[1];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;replaceQueryParams;;;MapValue of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;replaceQueryParams;;;MapKey of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;scheme;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilder;true;userInfo;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriBuilderFactory;true;builder;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;UriBuilderFactory;true;uriString;;;Argument[-1..0];ReturnValue;taint",
        "org.springframework.web.util.UriComponents;UriTemplateVariables;true;uriString;;;MapValue of Argument[-1];ReturnValue;taint",
        // note for review: I'm considereding UriComponents (like URI) to be one entity and not bothering adding synthetic fields for its components
        "org.springframework.web.util;UriComponents;false;copyToUriComponentsBuilder;;;Argument[-1];Argument[0];taint",
        "org.springframework.web.util;UriComponents;false;encode;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;UriComponents;false;expand;(java.util.Map<java.lang.String,?>);;MapValue of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponents;false;expand;(java.lang.Object...);;Element of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponents;false;expand;(org.springframework.web.util.UriComponents;UriTemplateVariables);;MapValue of Argument[0];ReturnValue;taint",
        // some excluded to avoid FPs
        "org.springframework.web.util;UriComponents;false;getFragment;;;Argument[-1];ReturnValue;taint",
        // "org.springframework.web.util;UriComponents;false;getHost;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;UriComponents;false;getPath;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;UriComponents;false;getPathSegments;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;UriComponents;false;getQuery;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;UriComponents;false;getQueryParams;;;Argument[-1];MapKey of ReturnValue;taint",
        "org.springframework.web.util;UriComponents;false;getQueryParams;;;Argument[-1];MapValue of ReturnValue;taint",
        // "org.springframework.web.util;UriComponents;false;getScheme;;;Argument[-1];MapValue of ReturnValue;taint",
        // "org.springframework.web.util;UriComponents;false;getSchemeSpecificPart;;;Argument[-1];MapValue of ReturnValue;taint",
        "org.springframework.web.util;UriComponents;false;getUserInfo;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;UriComponents;false;toUri;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;UriComponents;false;toUriString;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;build;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;build;(java.util.Map<java.lang.String,?>);;MapValue of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;build;(java.lang.Object...);;Element of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;buildAndExpand;(java.util.Map<java.lang.String,?>);;MapValue of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;buildAndExpand;(java.lang.Object...);;Element of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;cloneBuilder;;;Argument[-1];ReturnValue;value",
        "org.springframework.web.util;UriComponentsBuilder;false;fragment;;;Argument[0];ReturnValue;taint",
        // note for review: this takes an HttpRequest; if Joe's models of it use synthetic fields then this should as well
        "org.springframework.web.util;UriComponentsBuilder;false;fromHttpRequest;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;fromHttpUrl;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;fromOriginHeader;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;fromPath;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;fromUri;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;fromUriString;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;host;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;parseForwardedFor;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;parseForwardedFor;;;Argument[0];Argument[1];taint",
        "org.springframework.web.util;UriComponentsBuilder;false;path;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;pathSegment;;;Element of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;port;(java.lang.String);;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;query;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;queryParam;;;Argument[0];ReturnValue;taint",
        // note for review: using `Element of` for `Object...` here
        "org.springframework.web.util;UriComponentsBuilder;false;queryParam;;;Element of Argument[1];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;queryParamIfPresent;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;queryParamIfPresent;;;Element of Argument[1];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;queryParams;;;MapValue of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;queryParams;;;MapKey of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;replacePath;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;replaceQuery;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;replaceQueryParam;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;replaceQueryParam;;;Element of Argument[1];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;replaceQueryParams;;;MapValue of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;replaceQueryParams;;;MapKey of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;scheme;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;schemeSpecificPart;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;toUriString;;;Argument[-1];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;uri;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;uriComponents;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;uriVariables;;;MapValue of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriComponentsBuilder;false;userInfo;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriTemplate;false;expand;;;MapValue of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriTemplate;false;expand;;;Element of Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriTemplate;false;match;;;Argument[0];MapValue of ReturnValue;taint",
        // note for review: are encodings considered value-preserving?
        "org.springframework.web.util;UriUtils;false;decode;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encode;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodeAuthority;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodeFragment;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodeHost;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodePath;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodePathSegment;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodePort;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodeQuery;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodeQueryParam;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodeQueryParams;;;MapKey of Argument[0];MapKey of ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodeQueryParams;;;MapValue of Argument[0];MapValue of ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodeScheme;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodeUriVariables;(java.util.Map<java.lang.String,?>);;MapValue of Argument[0];MapValue of ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodeUriVariables;(java.util.Map<java.lang.String,?>);;MapKey of Argument[0];MapKey of ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodeUriVariables;(Object...);;Element of Argument[0];Element of ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;encodeUserInfo;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UriUtils;false;extractFileExtension;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UrlPathHelper;false;decodeMatrixVariables;;;Argument[0];MapValue of ReturnValue;taint",
        "org.springframework.web.util;UrlPathHelper;false;decodeMatrixVariables;;;Argument[0];MapValue of Argument[1];taint",
        "org.springframework.web.util;UrlPathHelper;false;decodePathVariables;;;Argument[0];MapValue of Argument[1];taint",
        "org.springframework.web.util;UrlPathHelper;false;decodePathVariables;;;Argument[0];MapValue of ReturnValue;taint",
        "org.springframework.web.util;UrlPathHelper;false;decodeRequestString;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UrlPathHelper;false;getContextPath;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UrlPathHelper;false;getOriginatingContextPath;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UrlPathHelper;false;getOriginatingQueryString;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UrlPathHelper;false;getOriginatingRequestUri;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UrlPathHelper;false;getOriginatingServletPath;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UrlPathHelper;false;getRequestUri;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UrlPathHelper;false;getResolvedLookupPath;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UrlPathHelper;false;getServletPath;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UrlPathHelper;false;removeSemicolonContent;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;UrlPathHelper;false;resolveAndCacheLookupPath;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;WebUtils;false;findParameterValue;(java.util.Map<java.lang.String,?>);;MapValue of Argument[0];ReturnValue;value",
        "org.springframework.web.util;WebUtils;false;findParameterValue;(javax.servlet.ServletRequest);;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;WebUtils;false;getCookie;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;WebUtils;false;getNativeRequest;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;WebUtils;false;getNativeResponse;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;WebUtils;false;getParametersStartingWith;;;Argument[0];MapKey of ReturnValue;taint",
        "org.springframework.web.util;WebUtils;false;getParametersStartingWith;;;Argument[0];MapValue of ReturnValue;taint",
        "org.springframework.web.util;WebUtils;false;getRealPath;;;Argument[1];ReturnValue;taint",
        "org.springframework.web.util;WebUtils;false;getRequiredSessionAttribute;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;WebUtils;false;getSessionAttribute;;;Argument[0];ReturnValue;taint",
        "org.springframework.web.util;WebUtils;false;parseMatrixVariables;;;Argument[0];MapKey of ReturnValue;taint",
        "org.springframework.web.util;WebUtils;false;parseMatrixVariables;;;Argument[0];MapValue of ReturnValue;taint",
      ]
    }
  }
}
